FROM alpine:3.14

WORKDIR /app
ENV GROUPSIO_GROUP_NAME='<GROUPSIO-GROUP-NAME>'
ENV GROUPSIO_EMAIL='<GROUPSIO-EMAIL>'
ENV GROUPSIO_PASSWORD='<GROUPSIO-PASSWORD>'
ENV GROUPSIO_SAVE_ARCHIVES='<GROUPSIO-SAVE_ARCHIVES>'
ENV ES_URL='<ES-URL>'
ENV STAGE='<STAGE>'
ENV ELASTIC_LOG_URL='<ELASTIC-LOG-URL>'
ENV ELASTIC_LOG_USER='<ELASTIC-LOG-USER>'
ENV ELASTIC_LOG_PASSWORD='<ELASTIC-LOG-PASSWORD>'
# RUN apk update
RUN apk update && apk add --no-cache bash && apk add gcompat
RUN ls -ltra
COPY groupsio ./
CMD ./groupsio --groupsio-group-name="${GROUPSIO_GROUP_NAME}" --groupsio-es-url="${ES_URL}" --groupsio-email="${GROUPSIO_EMAIL}" --groupsio-password="${GROUPSIO_PASSWORD}}" --groupsio-save-archives="${GROUPSIO_SAVE_ARCHIVES}"
